
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  servlet:
    contextPath:   /auth

spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: true
    properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
    properties.hibernate.jdbc.lob.non_contextual_creation: "true"
    properties.hibernate.temp.use_jdbc_metadata_defaults: "false"
    hibernate.ddl-auto: "create-drop"
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://eagle-eye-aws-dev2.cawltda6eb1j.ap-northeast-2.rds.amazonaws.com/eagle_eye_aws_dev"
    username: "eagle_eye_aws_dev"
    password: "mypassword"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "org.postgresql.Driver"

signing.key: "345345fsdfsf5345"
